### ISSUE TITLE
请问mitojs和monitor是什么关系？

### ISSUE THREAD

**Issue by pany-ang** [mitojs/mitojs#11]
哈喽，请问mitojs和monitor是什么关系？一时不知道该选择谁？

**Comment by pany-ang** [comment]
好像monitor是mitojs的前身？但是monitor似乎又在持续更新中

**Comment by cjinhuo** [comment]
> 好像monitor是mitojs的前身？但是monitor似乎又在持续更新中

嗯 是的 monitor 里面包含了性能监控 和 错误监控，mitojs 目前只有错误监控（重构了旧版的代码，更多hook、多实例、插件模型）
