### ISSUE TITLE
兼容性：IE8中存在兼容性问题

### ISSUE THREAD

**Issue by Aubyn** [mitojs/mitojs#13]
项目 README 中，写到 browser 版支持 IE>=8，我测试了一下，遇到下面的情况，**想确认一下是否确实支持 IE8 呢**

我根据 [集成文档](https://mitojs.github.io/mito-doc/#/zh-CN/sdk/guide/browser)，使用 CDN 的方式引入到测试页面并启用。

![image](https://user-images.githubusercontent.com/20233726/163665171-3585a84d-32e0-48ed-ba62-bb4620beb483.png)

在 IE11 中打开测试页面，修改文档模式为 IE8，控制台报错，无法使用 SDK。

![image](https://user-images.githubusercontent.com/20233726/163665063-a2dce394-d4bd-4085-89ef-d34763d87b5f.png)

我看了源码中的 on 方法，直接用 addEventListener 来注册事件处理程序，未加兼容性处理

![image](https://user-images.githubusercontent.com/20233726/163665218-34fc1ff8-0559-4538-acb2-6504b6d174b9.png)

**Comment by cjinhuo** [comment]
那就IE9 😳
