### ISSUE TITLE
为什么要对breadcrumbs按照时间排序来解决ajax和click事件的先后顺序问题？

### ISSUE THREAD

**Issue by liuyiqi1999** [mitojs/mitojs#14]
我在看 breadcrumbs 的相关代码，看到推入用户行为栈的部分：
```
private immediatePush(data: BreadcrumbPushData): BreadcrumbPushData[] {
    data.time || (data.time = getTimestamp())
    if (this.stack.length >= this.maxBreadcrumbs) {
      this.shift()
    }
    this.stack.push(data)
    // make sure xhr fetch is behind button click
    this.stack.sort((a, b) => a.time - b.time)
    logger.log(this.stack)
    return this.stack
  }
```

我注意到这里对stack做了一个按照time的排序，看注释是用于解决ajax和click事件顺序与实际不符的问题。
我自己实验了一下，对button和window分别设置监听：
```
<body>
    <button id="button">button</button>
    <script>
        const button = document.getElementById('button');
        button.addEventListener('click', () => {
            console.log('button click');
        })
    
        window.addEventListener('click', ()=> {
            console.log('window click');
        }, true)
    </script>
</body>
```
点击button后，可以看到是window的监听回调先触发，然后才是button自己的回调：
<img width="231" alt="image" src="https://user-images.githubusercontent.com/42669906/163682905-fad24271-f5b2-4641-a9cf-ee4db774abc6.png">

对应到按钮触发请求的场景中，也应该是window上监听点击事件的回调函数先触发，然后才是button自己发送ajax请求的回调。我理解JavaScript处理这两个回调函数应该是同步的，因此理论上不应该存在之前提到的ajax在click前的问题。

不过我观察到，click事件的time在采集时未指定，而是在immediatePush阶段才获取的。而ajax请求的time是在发送请求前就获取了time。虽然我自己觉得不应该影响结果才对。

不知道是我前面的理解有误，还是整个流程中的其他地方可能导致ajax比click先被推入用户行为栈这一现象。求解答，感谢！

**Comment by cjinhuo** [comment]
ajax不会比click优先入栈的，sort是为了排序button 和 ajax顺序

比如点了A -> 请求q1 耗时2s才返回，在此期间点了按钮B，如果不sort，顺序会是：A - B - q1，

sort后：A - q1 - B
