### ISSUE TITLE
关于异常“场景回放”的探讨

### ISSUE THREAD

**Issue by dengBox** [mitojs/mitojs#2]
**Describe the bug**
首先感谢作者开源此项目，对实现前端监控有很大帮助。目前我这边也有前端监控的诉求，调研了许久方案。对于监控数据的收集都是大同小异，请问作者对于异常场景回放的方案有什么思路吗？

**Expected behavior**
下面是我想到的两种思路：
1. 我这边调研到基于dom更新去做一系列数据“存档”，在错误发生时，将用户行为收集 进行回放。
2. 针对特有框架诸如'Vue，react'进行mixin混入劫持路由级别的组件数据，然后基于源码进行回放。
不知道 除了这种方式的’回放‘坐着 还有其他方案吗？

**Information**
 - [rrweb](https://github.com/rrweb-io/rrweb)

**Comment by cjinhuo** [comment]
> **Describe the bug**
> 首先感谢作者开源此项目，对实现前端监控有很大帮助。目前我这边也有前端监控的诉求，调研了许久方案。对于监控数据的收集都是大同小异，请问作者对于异常场景回放的方案有什么思路吗？
> 
> **Expected behavior**
> 下面是我想到的两种思路：
> 
> 1. 我这边调研到基于dom更新去做一系列数据“存档”，在错误发生时，将用户行为收集 进行回放。
> 2. 针对特有框架诸如'Vue，react'进行mixin混入劫持路由级别的组件数据，然后基于源码进行回放。
>    不知道 除了这种方式的’回放‘坐着 还有其他方案吗？
> 
> **Information**
> 
> * [rrweb](https://github.com/rrweb-io/rrweb)

我在上家公司也是采用`rrweb`的方式来录制，也是在线上正常运行了几个月，用谷歌自带的api:[mutationobserver](https://wangdoc.com/javascript/dom/mutationobserver.html)检测到节点的变化，可以做到兼容所有框架
