### ISSUE TITLE
vue 项目使用的时候有 ts 类型错误

### ISSUE THREAD

**Issue by xuxchao** [mitojs/mitojs#24]
按照官网正常安装出现的 bug

![image](https://user-images.githubusercontent.com/28293069/223301435-4be9df1e-19f1-48a5-87d2-f2d3424c37d1.png)

**Comment by cjinhuo** [comment]
> 按照官网正常安装出现的 bug
> 
> ![image](https://user-images.githubusercontent.com/28293069/223301435-4be9df1e-19f1-48a5-87d2-f2d3424c37d1.png)

贴个 在线代码地址，codesandbox 或 StackBlitz之类的

**Comment by xuxchao** [comment]
> 

![image](https://user-images.githubusercontent.com/28293069/223303008-77628ee5-ecc3-46c2-94cb-7bf10e55d06d.png)

ts 配置如下：
![image](https://user-images.githubusercontent.com/28293069/223303310-f65c2b4c-462e-4b1e-a939-86a67d49c057.png)

看起来是 ts 严格模式导致的，我主动加入 "strict": false, 就不报错了

**Comment by xuxchao** [comment]
不能支持一下严格模式么？

**Comment by xuxchao** [comment]
"@mitojs/browser": "^3.0.1",
"@mitojs/vue": "^3.0.1",

**Comment by cjinhuo** [comment]
暂时不支持，一开始没有开启严格，现在开启成本有点大。 （将来这个库会重构）

**Comment by xuxchao** [comment]
有重构思路么，一起重构一下？

**Comment by cjinhuo** [comment]
优化 API 的暴露方式，后续添加 hook 类似：
const client = MITO.init({})
client.on('beforeDataReport',(e) => {})

添加 tiny rxjs 来做数据流的消费，把插件中的 monitor 改为多播 subject，transform 和 consumer 改为 自定义pipeline

**Comment by cjinhuo** [comment]
> 优化 API 的暴露方式，后续添加 hook 类似： const client = MITO.init({}) client.on('beforeDataReport',(e) => {})
> 
> 添加 tiny rxjs 来做数据流的消费，把插件中的 monitor 改为多播 subject，transform 和 consumer 改为 自定义pipeline

> 有重构思路么，一起重构一下？

还有 配置热更新 等等

**Comment by cjinhuo** [comment]
> 有重构思路么，一起重构一下？

最近在忙其他的  到时重构开始  我会在群里放个 Roadmap 看看你要不要一起
