### ISSUE TITLE
建议可以支持单个包打包构建

### ISSUE THREAD

**Issue by 0522skylar** [mitojs/mitojs#27]
**Describe the bug**
目前打包是rollup，并且一次build，各个包都重新构建一次，速度过慢，可以单个packages支持单个打包构建

**Expected behavior**
可以尝试使用tsup构建，速度能够快很多

**Information**
 - Mitojs Version [e.g. v3.0.1]
 - Environment: [e.g. Vue2.6、Vue3.0、React17.0]
 - Error info stack [e.g. MITO is not defined]

**Comment by cjinhuo** [comment]
可以单个包build，你试下 npm run build browser
<img width="830" alt="image" src="https://github.com/mitojs/mitojs/assets/22608658/eb1dba27-c5fb-4312-b95f-314e63e304a1">
